### ISSUE TITLE
API improvement: invalidation

### ISSUE THREAD

**Issue by vpmedia** [jonathanhart/pixelmask#7]
First of all thanks for sharing this class!
During development i've ran into an issue that i don't want to set animated property to 'true' but i wan't to manually update the render state.
So i think it would be useful to add this method:

```
public function invalidate():void {
    _maskRendered = false;
}
```

Cheers

**Comment by soccerob** [comment]
I think this class still needs the ability to do the above mentioned code at some point. If I set up the pixelMask with _animated=false and then later on add another child to the pixelMask, it will never be reflected. 

I changed my code to add the following, which I'm not sure if this violates the idea of the method that I'm overriding, but it gets the job done for me and allows me to add more children to the pixelMask and have it be reflected on screen.
		
`override public function setRequiresRedraw():void {
	super.setRequiresRedraw();
	_maskRendered = false;
}`
